chris = User.create(first_name: "Chris", last_name: "Diep", email: "diep.christopher@gmail.com")
rick = User.create(first_name: "Rick", last_name: "Nilon", email: "r.nilon92@gmail.com")
nyc = Place.create(city: "New York City", country: "United States")
tokyo = Place.create(city: "Tokyo", country: "Japan")
sf = Place.create(city: "San Francisco", country: "United States")
